### ISSUE TITLE
Requesting IncludeStatus throws DateTime.Parse exception

### ISSUE THREAD

**Issue by derekantrican** [viceroypenguin/Going.Plaid#96]
The following:
```csharp
var statusResult = await Settings.PlaidClient.InstitutionsGetByIdAsync(new Going.Plaid.Institutions.InstitutionsGetByIdRequest()
{
    InstitutionId = "ins_3",
    CountryCodes = new[]
    {
        Going.Plaid.Entity.CountryCode.Us,
    },
    Options = new Going.Plaid.Entity.InstitutionsGetByIdRequestOptions()
    {
        IncludeStatus = true,
    },
});
```

Throws the following exception:
```
An unhandled exception has occurred while executing the request.
      System.FormatException: String '' was not recognized as a valid DateTime.       
         at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
         at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, 
DateTimeStyles styles)
         at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider) 
         at Going.Plaid.Converters.DateTimeOffsetConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
...
```

I also tested this with a different institution (`ins_12` - Fidelity) and got the same result

**Comment by derekantrican** [comment]
Another test: Wells Fargo (`ins_4`) seems to work, however a number of the values are null:

```json
"Status": {
  "ItemLogins": null,
  "TransactionsUpdates": null,
  "Auth": null,
  "Identity": null,
  "InvestmentsUpdates": null,
  "LiabilitiesUpdates": null,
  "Liabilities": null,
  "Investments": null,
  "HealthIncidents": [{
    "StartDate": "2021-12-02T04:27:00+00:00",
    "EndDate": "2022-12-31T19:59:00+00:00",
    "Title": "Institution Deprecation",
    "IncidentUpdates": [{
      "Description": "You're viewing status data for ins_4, our legacy Wells Fargo integration. This data is relevant for existing ins_4 items. To view status data for our new Wells Fargo OAuth integration, please see status information for ins_127991. If you are enabled, all new Wells Fargo item adds will be routed through ins_127991. 
If you have questions please contact Plaid Support.",
      "Status": 2,
      "UpdatedDate": "2021-12-02T04:26:47+00:00"
    }]
  }]
}
```

**Comment by viceroypenguin** [comment]
Looks like there is a discrepancy between the published specification of the response and the actual response, specifically that `HeathIncident.end_date` is non-nullable when certain responses do have a `null` value for that property. I have reported it [upstream](plaid/plaid-openapi#106) so that the specification will be fixed. 

I am also preparing a v4.15.1 bugfix release to address this in the meantime. (d4d81bb1212a6938b6bc4f1b1c9ba4e020c63352)
